library(readxl)
library(dplyr)
library(stringr)
DATA2 <- read_xlsx(path="DATA(variable renamed) 2(1).xlsx")
DATA2$年級 <-as.numeric(DATA2$年級) 
DATA2$是否住宿 <-as.numeric(DATA2$是否住宿) 
DATA2$常使用的是 <-as.numeric(DATA2$常使用的是) 
DATA2$什麼時候開始使用外送平台 <-as.numeric(DATA2$什麼時候開始使用外送平台) 
DATA2$什麼時候開始使用外送平台[is.na(DATA2$什麼時候開始使用外送平台)] <- 0
str(DATA2)
A2 <- DATA2[DATA2$是否住宿 %in% 2 & DATA2$常使用的是 %in% 2, ]
A2$早餐 <- str_extract(string = A2$一天什麼時候會使用外送平台, pattern="1")
A2$午餐 <- str_extract(string = A2$一天什麼時候會使用外送平台, pattern="2")
A2$晚餐 <- str_extract(string = A2$一天什麼時候會使用外送平台, pattern="3")
A2$點心飲料 <- str_extract(string = A2$一天什麼時候會使用外送平台, pattern="4")
A2$宵夜 <- str_extract(string = A2$一天什麼時候會使用外送平台, pattern="5")
nrow(A2[A2$早餐 %in% 1, ])
nrow(A2[A2$午餐 %in% 2, ])
nrow(A2[A2$晚餐 %in% 3, ])
nrow(A2[A2$點心飲料 %in% 4, ])
nrow(A2[A2$宵夜 %in% 5, ])